"""add user_id to outcomes

Revision ID: 75ea1b948b2a
Revises: 97807b9a3c89
Create Date: 2026-08-05 17:37:46.419264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ea1b948b2a'
down_revision: Union[str, Sequence[str], None] = '97807b9a3c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcomes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_outcomes_user_id'), 'outcomes', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_outcomes_user_id_users'), 'outcomes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_outcomes_user_id_users'), 'outcomes', type_='foreignkey')
    op.drop_index(op.f('ix_outcomes_user_id'), table_name='outcomes')
    op.drop_column('outcomes', 'user_id')
    # ### end Alembic commands ###
