"""add user_id to job_descriptions

Revision ID: 97807b9a3c89
Revises: bd31568efd53
Create Date: 2026-07-30 20:24:08.005480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97807b9a3c89'
down_revision: Union[str, Sequence[str], None] = 'bd31568efd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_job_descriptions_user_id_users'), 'job_descriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_job_descriptions_user_id_users'), 'job_descriptions', type_='foreignkey')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_column('job_descriptions', 'user_id')
    # ### end Alembic commands ###
